import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BookOpen, Check, Compass, Flag, MapPin, Plus, Save, Shield, Swords, Trash2 } from 'lucide-react'
import { api } from './api'
import type { Dashboard } from './types'
import type { Adventure, AdventureBudget, AdventureDraft, AdventureResource, AdventureTemplate, EnemyGroup } from './adventureTypes'
import './AdventureStudio.css'

const difficulty:Record<string,string> = {trivial:'Trivial',easy:'Fàcil',medium:'Mitjana',hard:'Difícil',deadly:'Mortal'}
const status:Record<string,string> = {draft:'Preparada',active:'En joc',completed:'Finalitzada'}
const terrains:Record<string,string> = {jungle:'Selva',forest:'Bosc',ruins:'Ruïnes',river:'Riu',swamp:'Pantà',dungeon:'Dungeon',urban:'Ciutat',mountain:'Muntanya',coast:'Costa',desert:'Desert'}
const labels:Record<string,string> = {hook:'Ganxo',rooms:'Sales',name:'Nom',description:'Descripció',hazard:'Perill',reward:'Recompensa',secret:'Secret',setup:'Preparació',checks:'Proves',dc:'CD',ability:'Habilitat',success:'Èxit',failure:'Fracàs',twists:'Complicacions',target:'Objectiu',danger_max:'Perill màxim',round_limit:'Límit de rondes',prompt:'Situació inicial',choices:'Opcions',label:'Opció',check:'Prova',twist:'Gir',follow_up:'Continuïtat',tactics:'Tàctiques',salvage:'Botí',traits:'Trets',actions:'Accions'}

function ResourceDetails({value}:{value:unknown}) {
  if (value === null || value === undefined) return null
  if (Array.isArray(value)) return <ul>{value.map((item,i)=><li key={i}><ResourceDetails value={item}/></li>)}</ul>
  if (typeof value === 'object') return <dl>{Object.entries(value).map(([key,item])=><div key={key}><dt>{labels[key]??key.replaceAll('_',' ')}</dt><dd><ResourceDetails value={item}/></dd></div>)}</dl>
  return <span>{String(value)}</span>
}

function BudgetPanel({budget}:{budget:AdventureBudget|null}) {
  return <section className="adv-budget"><span className="eyebrow">D&D 5e · regles 2014</span><h2>Pressupost de trobada</h2>
    {!budget ? <p>Tria els enemics per estimar-ne la dificultat.</p> : <>
      <p>{budget.levels.length} personatges · nivells {budget.levels.join(', ')}<br/><small>{budget.party_source==='characters'?'Fitxes actives de la campanya':'Configuració del grup (sense fitxes actives)'}</small></p>
      <div className="adv-thresholds">{budget.thresholds.map((n,i)=><div key={i}><span>{['Fàcil','Mitjana','Difícil','Mortal'][i]}</span><b>{n.toLocaleString()}</b></div>)}</div>
      {budget.waves.map(w=><div className={`adv-wave ${w.difficulty}`} key={w.wave}><div><b>Onada {w.wave}</b><span>{difficulty[w.difficulty]}</span></div><strong>{w.adjusted_xp.toLocaleString()} <small>PX ajustats</small></strong><p>{w.count} enemics · {w.xp} PX base × {w.multiplier}</p><meter min={0} max={Math.max(budget.thresholds[3]*1.3,w.adjusted_xp)} value={w.adjusted_xp} aria-label={`Risc onada ${w.wave}`}/></div>)}
      <p className="adv-xp"><b>{budget.total_xp.toLocaleString()} PX base</b> · sense repartiment automàtic</p>
      <details><summary>Com s'ha calculat?</summary>{budget.warnings.map(w=><p key={w}>{w}</p>)}<a href="https://www.dndbeyond.com/sources/dnd/basic-rules-2014/building-combat-encounters" target="_blank" rel="noreferrer">Font: Basic Rules 2014 ↗</a></details>
    </>}
  </section>
}

function SceneChecks({adventure,busy,run}:{adventure:Adventure;busy:boolean;run:(action:()=>Promise<Adventure>)=>Promise<void>}) {
  const [index,setIndex]=useState(0)
  const [modifier,setModifier]=useState(0)
  const [manual,setManual]=useState(false)
  const [d20,setD20]=useState(10)
  const step=adventure.data.steps[adventure.data.current_step]
  const checks=(step.resource?.data.checks??[]) as {name:string;ability:string;dc:number}[]
  const results=step.check_results??[]
  const latest=results[results.length-1]
  if(!checks.length)return null
  return <section className="adv-checks"><h3>Proves a taula</h3><div className="adv-two"><label>Prova<select aria-label="Prova" value={index} onChange={e=>setIndex(Number(e.target.value))}>{checks.map((c,i)=><option key={i} value={i}>{c.name} · CD {c.dc}</option>)}</select></label><label>Modificador<input type="number" min={-20} max={30} value={modifier} onChange={e=>setModifier(Math.max(-20,Math.min(30,Number(e.target.value)||0)))}/></label></div><p className="adv-muted">{checks[index]?.ability}</p><label className="adv-check"><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/> Els jugadors tiren els daus físics</label>{manual&&<label>Resultat natural del d20<input type="number" min={1} max={20} value={d20} onChange={e=>setD20(Math.max(1,Math.min(20,Number(e.target.value)||1)))}/></label>}<button disabled={busy} onClick={()=>void run(()=>api.adventureCheck(adventure.id,adventure.data.revision,index,modifier,manual?d20:null))}>{manual?'Registrar tirada':'Tirar d20'}</button><p className="adv-muted">Registra total i CD. El DM aplica les regles particulars, compta rondes i decideix les conseqüències; un 20 no supera automàticament una prova d'habilitat.</p>{latest&&<><div className="adv-roll-result"><b>{latest.total}</b><span>{latest.success?'Èxit':'Fracàs'} · CD {latest.dc}</span></div><details><summary>Historial de proves · {results.length}</summary>{results.map((r,i)=><p key={i}>{r.name}: {r.d20} {r.modifier<0?'−':'+'} {Math.abs(r.modifier)} = <b>{r.total}</b> / CD {r.dc} · {r.success?'èxit':'fracàs'} · {r.manual?'manual':'automàtica'}</p>)}</details></>}</section>
}

export function AdventureStudio({data,changed}:{data:Dashboard;changed:()=>void}) {
  const [tab,setTab]=useState<'prepare'|'play'>(data.campaign_records.some(r=>r.kind==='adventure')?'play':'prepare')
  const [resources,setResources]=useState<AdventureResource[]>([])
  const [templates,setTemplates]=useState<AdventureTemplate[]>([])
  const [records,setRecords]=useState<Adventure[]>(()=>data.campaign_records.filter(r=>r.kind==='adventure') as Adventure[])
  const [selected,setSelected]=useState(new URLSearchParams(location.search).get('adventure')??'')
  const [draft,setDraft]=useState<AdventureDraft>({campaign_id:data.campaign.id,title:'',description:'',hex_id:null,location_id:null,situation_id:null,temple_id:null,minigame_id:null,enemy_groups:[],alert_delta:0,include_characters:true})
  const [terrain,setTerrain]=useState('jungle')
  const [search,setSearch]=useState('')
  const [enemyId,setEnemyId]=useState('')
  const [budget,setBudget]=useState<AdventureBudget|null>(null)
  const [error,setError]=useState('')
  const [busy,setBusy]=useState(false)
  const [note,setNote]=useState('')
  const [message,setMessage]=useState('')
  useEffect(()=>{let live=true;Promise.all([api.adventureResources(),api.adventureTemplates()]).then(([r,t])=>{if(live){setResources(r);setTemplates(t)}}).catch(e=>{if(live)setError(String(e))});return()=>{live=false}},[])
  useEffect(()=>{let live=true;const timer=setTimeout(()=>{api.adventureBudget(data.campaign.id,draft.enemy_groups).then(b=>{if(live)setBudget(b)}).catch(e=>{if(live){setBudget(null);setError(String(e))}})},200);return()=>{live=false;clearTimeout(timer)}},[data.campaign.id,draft.enemy_groups])
  const enemies=useMemo(()=>resources.filter(r=>['enemy','monsters'].includes(r.category)&&(!search||`${r.name} ${r.summary}`.toLowerCase().includes(search.toLowerCase()))&&(!terrain||!('terrains' in r)||r.terrains.includes(terrain))),[resources,search,terrain])
  const current=records.find(r=>r.id===selected)??records.find(r=>r.status==='active')??records[0]
  const step=current?.data.steps[current.data.current_step]
  const run=async(action:()=>Promise<Adventure>,clearNote=false)=>{
    if(busy)return
    setBusy(true);setError('');setMessage('')
    try{const record=await action();setRecords(old=>[record,...old.filter(r=>r.id!==record.id)]);setSelected(record.id);setTab('play');if(clearNote)setNote('');changed()}
    catch(e){setError(e instanceof Error?e.message:'No s’ha pogut completar');try{setRecords(await api.records(data.campaign.id,'adventure') as Adventure[])}catch{/* Keep the current view if offline. */}}
    finally{setBusy(false)}
  }
  const groupChange=(index:number,patch:Partial<EnemyGroup>)=>setDraft(d=>({...d,enemy_groups:d.enemy_groups.map((g,i)=>i===index?{...g,...patch}:g)}))
  const applyTemplate=(t:AdventureTemplate)=>{setDraft(d=>({...d,title:t.title,description:t.description,situation_id:t.situation_id,temple_id:t.temple_id,minigame_id:t.minigame_id,enemy_groups:t.enemy_groups.map(g=>({...g}))}));setTerrain(t.terrain);setMessage('Plantilla carregada. Pots modificar qualsevol selecció abans de desar.')}
  const resourceSelect=(category:string,field:'situation_id'|'temple_id'|'minigame_id',label:string)=><label>{label}<select aria-label={label} value={draft[field]??''} onChange={e=>setDraft({...draft,[field]:e.target.value||null})}><option value="">Sense aquesta escena</option>{resources.filter(r=>r.category===category).map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>
  const advance=(force=false)=>current&&run(()=>api.adventureAction(current.id,'advance',current.data.revision,note,force),true)
  return <div className="adventure-studio">
    <div className="studio-heading"><div><span className="eyebrow">Adventure desk · v1.4</span><h1>De la idea a la partida</h1><p>Prepara una ruta d'escenes. Dirigeix-la al teu ritme, amb el control sempre a les teves mans.</p></div><Compass/></div>
    <div className="adv-toolbar"><div role="group" aria-label="Vista d'aventures"><button className={tab==='prepare'?'active':''} onClick={()=>setTab('prepare')}><Plus size={16}/> Preparar</button><button className={tab==='play'?'active':''} onClick={()=>setTab('play')}><Flag size={16}/> A taula <small>{records.length}</small></button></div><span><Shield size={15}/> Només DM · desat local</span></div>
    {error&&<div className="adv-error" role="alert">{error}</div>}{message&&<p className="adv-notice" role="status">{message}</p>}
    {tab==='prepare'?<>
      <details className="adv-templates" open={!draft.title}><summary><BookOpen size={16}/> Sis punts de partida originals <small>Homebrew · editables</small></summary><div>{templates.map(t=><button key={t.id} onClick={()=>applyTemplate(t)}><span>{terrains[t.terrain]}</span><strong>{t.title}</strong><small>{t.level_hint}</small></button>)}</div></details>
      <div className="adv-layout"><div className="adv-stack">
        <section className="adv-card"><div className="adv-section-title"><span>01</span><h2>Fil conductor</h2></div><label>Títol de l'aventura<input maxLength={200} placeholder="El temple que recordava la pluja…" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Ganxo, pistes i decisions<textarea maxLength={5000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Què necessita el grup? Què pot descobrir? Quines alternatives té?"/></label><div className="adv-three">{resourceSelect('situation','situation_id','Situació')}{resourceSelect('temple','temple_id','Temple')}{resourceSelect('minigame','minigame_id','Minijoc')}</div></section>
        <section className="adv-card"><div className="adv-section-title"><span>02</span><h2>Enemics i onades</h2><Swords size={19}/></div><p className="adv-muted">Barreja monstres SRD i enemics originals. Només la primera onada entrarà en obrir el combat.</p><div className="adv-two"><label>Terreny homebrew<select aria-label="Terreny homebrew" value={terrain} onChange={e=>setTerrain(e.target.value)}><option value="">Tots els terrenys</option>{Object.entries(terrains).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Cerca d'enemics<input placeholder="Jaguar, goblin, serpent…" value={search} onChange={e=>{setSearch(e.target.value);setEnemyId('')}}/></label></div><small className="adv-muted">Els monstres SRD no tenen filtre d'hàbitat; comprova que encaixin amb la ubicació.</small><div className="adv-add"><label>Enemic<select aria-label="Enemic" value={enemyId} onChange={e=>setEnemyId(e.target.value)}><option value="">Tria entre {enemies.length} recursos</option>{enemies.map(e=><option key={e.id} value={e.id}>{e.name} · {String(e.data.xp??0)} PX {e.category==='enemy'?'· homebrew':'· SRD'}</option>)}</select></label><button disabled={!enemyId||draft.enemy_groups.length>=12} onClick={()=>setDraft({...draft,enemy_groups:[...draft.enemy_groups,{resource_id:enemyId,quantity:1,wave:1}]})}><Plus size={16}/> Afegir</button></div>
          {!draft.enemy_groups.length&&<p className="adv-empty">Cap combat obligatori. Una aventura també pot ser només exploració i conversa.</p>}
          {draft.enemy_groups.map((g,i)=>{const r=resources.find(r=>r.id===g.resource_id);return <div className="adv-enemy" key={`${i}-${g.resource_id}`}><div><strong>{r?.name??g.resource_id}</strong><small>{r?.category==='enemy'?'Homebrew original':'SRD 5.1'} · {String(r?.data.xp??0)} PX / criatura</small></div><label>Quantitat<input type="number" min={1} max={20} value={g.quantity} onChange={e=>groupChange(i,{quantity:Math.max(1,Math.min(20,Number(e.target.value)||1))})}/></label><label>Onada<select value={g.wave} onChange={e=>groupChange(i,{wave:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><button aria-label={`Treure ${r?.name}`} onClick={()=>setDraft({...draft,enemy_groups:draft.enemy_groups.filter((_,n)=>n!==i)})}><Trash2 size={16}/></button></div>})}
        </section>
        <details className="adv-card"><summary><MapPin size={16}/> Vincle amb el món i opcions</summary><div className="adv-two"><label>Hexàgon<select aria-label="Hexàgon" value={draft.hex_id??''} onChange={e=>setDraft({...draft,hex_id:e.target.value||null})}><option value="">Sense vincle</option>{data.hex_cells.map(h=><option key={h.id} value={h.id}>{h.q},{h.r} · {h.title||terrains[h.terrain]||h.terrain}</option>)}</select></label><label>Ubicació<select aria-label="Ubicació" value={draft.location_id??''} onChange={e=>setDraft({...draft,location_id:e.target.value||null})}><option value="">Sense vincle</option>{data.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div><label>Alerta en activar: +{draft.alert_delta}<input type="range" min={0} max={5} value={draft.alert_delta} onChange={e=>setDraft({...draft,alert_delta:Number(e.target.value)})}/></label><p className="adv-muted">Opcional. S'aplica una sola vegada a l'hexàgon vinculat; màxim 5. No mou el grup ni revela el mapa.</p><label className="adv-check"><input type="checkbox" checked={draft.include_characters} onChange={e=>setDraft({...draft,include_characters:e.target.checked})}/> Incorporar les fitxes actives al combat</label></details>
        <button className="primary adv-save" disabled={busy||draft.title.trim().length<2||draft.enemy_groups.reduce((n,g)=>n+g.quantity,0)>60} onClick={()=>void run(()=>api.createAdventure({...draft,title:draft.title.trim()}))}><Save size={17}/> {busy?'Desant…':'Desar aventura preparada'}</button><small className="adv-muted">Fins a 12 grups i 60 enemics. Desar no activa combats, no consumeix recursos ni modifica l'alerta.</small>
      </div><aside><BudgetPanel budget={budget}/><div className="adv-tip"><Compass size={23}/><h3>Prepara possibilitats, no obligacions</h3><p>Els combats es poden resoldre parlant. Les recompenses i els efectes narratius sempre necessiten la decisió del DM.</p></div></aside></div>
    </>:<div className="adv-play-layout"><aside className="adv-records"><h2>Quadern d'aventures</h2>{records.map(r=><button key={r.id} className={r.id===current?.id?'active':''} onClick={()=>{setSelected(r.id);setNote('');setError('')}}><small>{status[r.status]??r.status}</small><strong>{r.title}</strong><span>{Math.min(r.data.current_step+1,r.data.steps.length)} / {r.data.steps.length} escenes</span></button>)}<button onClick={()=>setTab('prepare')}><Plus size={16}/> Nova aventura</button></aside>
      {!current?<section className="adv-card adv-empty"><Compass size={42}/><h2>La propera aventura comença aquí</h2><p>Escull un dels sis punts de partida o prepara una història pròpia.</p><button className="primary" onClick={()=>setTab('prepare')}>Obrir el constructor</button></section>:<div className="adv-stack"><section className="adv-card adv-session"><div className="adv-kicker"><span>{status[current.status]}</span><span><Shield size={13}/> Només DM</span></div><h2>{current.title}</h2><div className="adv-route">{current.data.steps.map((s,i)=><div key={i} className={`${s.completed_at?'done':''} ${i===current.data.current_step?'current':''}`}><span>{s.completed_at?<Check size={13}/>:i+1}</span><small>{s.title}</small></div>)}</div>
          {current.data.hex_id&&<p className="adv-muted"><MapPin size={14}/> {data.hex_cells.find(h=>h.id===current.data.hex_id)?.title??current.data.hex_id} · alerta en activar +{current.data.alert_delta}</p>}
          {current.status==='draft'?<><p>Tot preparat. L'activació obre la primera escena i aplica l'alerta configurada, sense publicar cap secret.</p><button className="primary" disabled={busy} onClick={()=>void run(()=>api.activateAdventure(current.id))}><Flag size={16}/> Començar aventura</button>{current.data.hex_id&&<details><summary>Activació fora de l'hexàgon</summary><button disabled={busy} onClick={()=>{if(confirm('Activar l’aventura sense moure el grup i aplicar l’alerta a l’hexàgon vinculat?'))void run(()=>api.activateAdventure(current.id,true))}}>Confirmar activació remota</button></details>}<details><summary>Previsualitzar totes les escenes</summary>{current.data.steps.map((s,i)=><article key={i}><h3>{i+1}. {s.title}</h3><p>{s.description}</p></article>)}</details></>:current.status==='completed'?<div className="adv-finished"><Check size={32}/><h3>Aventura finalitzada</h3><p>El diari conserva les decisions. El botí i els PX no s'han repartit automàticament.</p><a href="?view=party">Obrir grup i inventari →</a></div>:step&&<><div className="adv-scene"><span className="eyebrow">Escena {current.data.current_step+1} de {current.data.steps.length}</span><h3>{step.title}</h3><p>{step.description||'Presenta la situació i pregunta al grup què vol fer.'}</p>{step.resource&&<details open key={step.title}><summary>Guia de l'escena · {step.resource.category==='monsters'?'SRD':'homebrew'}</summary><div className="adv-resource"><ResourceDetails value={step.resource.data}/></div></details>}</div>
          {step.kind==='combat'&&<div className="adv-combat-controls"><a className="adv-link" href={`?view=combat&combat=${encodeURIComponent(current.data.combat_id??'')}`}><Swords size={17}/> Obrir iniciativa i punts de vida ↗</a><p>Onades activades: {current.data.released_waves.join(', ')} / {current.data.budget.waves.map(w=>w.wave).join(', ')}</p><button disabled={busy||current.data.released_waves.length>=current.data.budget.waves.length} onClick={()=>void run(()=>api.adventureAction(current.id,'wave',current.data.revision))}>Fer entrar la següent onada</button></div>}
          {step.kind==='minigame'&&<SceneChecks key={`${current.id}-${current.data.current_step}`} adventure={current} busy={busy} run={run}/>}
          <label>Decisions i notes de l'escena<textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Pactes, pistes descobertes, conseqüències pendents…"/></label><div className="adv-actions"><button disabled={busy||!note.trim()} onClick={()=>void run(()=>api.adventureAction(current.id,'note',current.data.revision,note),true)}><Save size={15}/> Desar nota</button><button className="primary" disabled={busy} onClick={()=>void advance()}>{current.data.current_step===current.data.steps.length-1?'Finalitzar aventura':'Següent escena'} <ArrowRight size={16}/></button></div>{step.kind==='combat'&&<details><summary>Resoldre sense completar el combat</summary><p>Per fugida, pacte o escena saltada. Tanca el combat i descarta les onades pendents sense donar PX.</p><button disabled={busy} onClick={()=>{if(confirm('Tancar el combat i descartar les onades pendents?'))void advance(true)}}>Confirmar resolució narrativa</button></details>}</>}
          {current.data.notes.length>0&&<details><summary>Diari de decisions · {current.data.notes.length}</summary>{current.data.notes.map((n,i)=><article className="adv-note" key={i}><small>{n.step} · {new Date(n.created_at).toLocaleString()}</small><p>{n.text}</p></article>)}</details>}
        </section><details className="adv-card"><summary>Pressupost de combat guardat en preparar</summary><BudgetPanel budget={current.data.budget}/></details></div>}
    </div>}
  </div>
}
