import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronRight, Dices, FolderUp, Landmark, Leaf, Package, Play, Plus, RotateCcw, Search, Shuffle, Skull, Sparkles, Star, Swords, Trash2, X } from 'lucide-react'
import { api } from './api'
import type { CampaignRecord, Dashboard, HomebrewCategory, HomebrewItem, HomebrewPack, PartySettings } from './types'

type Structured = Record<string,unknown>
type CheckOption = {name:string;ability:string;dc:number}
type ExpeditionKit = Record<HomebrewCategory,HomebrewItem>

const categories:HomebrewCategory[]=['enemy','temple','situation','minigame']
const categoryLabels:Record<HomebrewCategory,string>={enemy:'Enemics',temple:'Temples',situation:'Situacions',minigame:'Minijocs'}
const terrainLabels:Record<string,string>={jungle:'Selva',forest:'Bosc',swamp:'Pantà',river:'Riu',ruins:'Ruïnes',dungeon:'Dungeon',mountain:'Muntanya',urban:'Ciutat'}
const xpThresholds=[[25,50,75,100],[50,100,150,200],[75,150,225,400],[125,250,375,500],[250,500,750,1100],[300,600,900,1400],[350,750,1100,1700],[450,900,1400,2100],[550,1100,1600,2400],[600,1200,1900,2800],[800,1600,2400,3600],[1000,2000,3000,4500],[1100,2200,3400,5100],[1250,2500,3800,5700],[1400,2800,4300,6400],[1600,3200,4800,7200],[2000,3900,5900,8800],[2100,4200,6300,9500],[2400,4900,7300,10900],[2800,5700,8500,12700]]
const asObjects=(value:unknown):Structured[]=>Array.isArray(value)?value.filter((item):item is Structured=>typeof item==='object'&&item!==null):[]
const text=(value:unknown,fallback='')=>typeof value==='string'?value:fallback
const number=(value:unknown,fallback=0)=>typeof value==='number'?value:fallback
const pick=<T,>(values:T[])=>{if(!values.length)return undefined;const random=new Uint32Array(1);crypto.getRandomValues(random);return values[random[0]%values.length]}
const initialCategory=():HomebrewCategory=>{const value=new URLSearchParams(window.location.search).get('brew');return categories.includes(value as HomebrewCategory)?value as HomebrewCategory:'enemy'}
const buildExpedition=async(terrain:string,level:number,difficulty:number,packId:string)=>{const results=await Promise.all(categories.map(async kind=>{let result=await api.homebrew('',kind,terrain,level,difficulty,packId);if(!result.items.length&&difficulty)result=await api.homebrew('',kind,terrain,level,0,packId);return [kind,pick(result.items)] as const}));if(results.some(([,item])=>!item))throw new Error('No hi ha prou recursos compatibles per construir una expedició');return Object.fromEntries(results) as ExpeditionKit}

export function JungleToolkit({data,changed}:{data:Dashboard;changed:()=>void}){
  const [category,setCategory]=useState<HomebrewCategory>(initialCategory)
  const [terrain,setTerrain]=useState('')
  const [level,setLevel]=useState(data.party.level)
  const [difficulty,setDifficulty]=useState(0)
  const [query,setQuery]=useState('')
  const [packId,setPackId]=useState('')
  const [items,setItems]=useState<HomebrewItem[]>([])
  const [selected,setSelected]=useState<HomebrewItem|null>(null)
  const [packs,setPacks]=useState<HomebrewPack[]>([])
  const [packFile,setPackFile]=useState<File|null>(null)
  const [favorites,setFavorites]=useState<string[]>(()=>{try{const stored:unknown=JSON.parse(localStorage.getItem(`gm-ai-homebrew-favorites-${data.campaign.id}`)??'[]');return Array.isArray(stored)&&stored.every(item=>typeof item==='string')?stored:[]}catch{return[]}})
  const [favoriteOnly,setFavoriteOnly]=useState(false)
  const [expedition,setExpedition]=useState<ExpeditionKit|null>(null)
  const [combatId,setCombatId]=useState(data.combats.find(item=>item.status==='active')?.id??data.combats[0]?.id??'')
  const [quantity,setQuantity]=useState(1)
  const [checkIndex,setCheckIndex]=useState(0)
  const [modifier,setModifier]=useState(0)
  const [busy,setBusy]=useState(false)
  const [notice,setNotice]=useState('')
  const [error,setError]=useState('')

  const applyResult=(result:{items:HomebrewItem[]})=>{const requested=new URLSearchParams(window.location.search).get('item');setItems(result.items);setSelected(current=>result.items.find(item=>item.id===(current?.id??requested))??result.items[0]??null);setCheckIndex(0)}
  const load=async()=>{setBusy(true);setError('');try{applyResult(await api.homebrew(query,category,terrain,level,difficulty,packId))}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut carregar el pack')}finally{setBusy(false)}}
  const refreshPacks=()=>api.homebrewPacks().then(setPacks).catch(exception=>setError(exception instanceof Error?exception.message:'No s’han pogut carregar els packs'))
  useEffect(()=>{let active=true;api.homebrew('',category,terrain,level,difficulty,packId).then(result=>{if(active)applyResult(result)}).catch(exception=>{if(active)setError(exception instanceof Error?exception.message:'No s’ha pogut carregar el pack')});return()=>{active=false}},[category,terrain,level,difficulty,packId])
  useEffect(()=>{let active=true;api.homebrewPacks().then(result=>{if(active)setPacks(result)}).catch(exception=>{if(active)setError(exception instanceof Error?exception.message:'No s’han pogut carregar els packs')});return()=>{active=false}},[])
  useEffect(()=>{localStorage.setItem(`gm-ai-homebrew-favorites-${data.campaign.id}`,JSON.stringify(favorites))},[data.campaign.id,favorites])
  useEffect(()=>{if(new URLSearchParams(window.location.search).get('compose')!=='1')return;let active=true;buildExpedition(terrain,level,difficulty,packId).then(result=>{if(active)setExpedition(result)}).catch(exception=>{if(active)setError(exception instanceof Error?exception.message:'No s’ha pogut generar l’expedició')});return()=>{active=false}},[terrain,level,difficulty,packId])

  const visibleItems=favoriteOnly?items.filter(item=>favorites.includes(item.id)):items
  const preparedClock=useMemo(()=>selected?.category==='minigame'?data.campaign_records.find(record=>record.kind==='clock'&&record.data.pack_item_id===selected.id&&record.status==='active'):undefined,[data.campaign_records,selected])
  const checks=asObjects(selected?.data.checks).map(item=>({name:text(item.name,'Prova'),ability:text(item.ability,'Ability check'),dc:number(item.dc,12)}))
  const clockData=preparedClock?.data??{}
  const current=number(clockData.current);const maximum=Math.max(1,number(clockData.maximum,4));const danger=number(clockData.danger);const dangerMax=Math.max(1,number(clockData.danger_max,3));const round=number(clockData.round,1);const roundLimit=Math.max(1,number(clockData.round_limit,5))
  const resourceCount=packs.filter(pack=>pack.status==='ready').reduce((total,pack)=>total+pack.item_count,0)

  const choose=(item:HomebrewItem)=>{setCheckIndex(0);setSelected(item);const params=new URLSearchParams(window.location.search);params.set('view','homebrew');params.set('brew',item.category);params.set('item',item.id);history.replaceState(null,'',`${window.location.pathname}?${params}`)}
  const changeCategory=(value:HomebrewCategory)=>{const params=new URLSearchParams(window.location.search);params.set('view','homebrew');params.set('brew',value);params.delete('item');history.replaceState(null,'',`${window.location.pathname}?${params}`);setCategory(value)}
  const toggleFavorite=(id:string)=>setFavorites(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])
  const randomItem=()=>{const item=pick(visibleItems);if(item)choose(item)}

  const generateExpedition=async()=>{setBusy(true);setError('');try{setExpedition(await buildExpedition(terrain,level,difficulty,packId));const params=new URLSearchParams(window.location.search);params.set('compose','1');history.replaceState(null,'',`${window.location.pathname}?${params}`)}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut generar l’expedició')}finally{setBusy(false)}}
  const closeExpedition=()=>{setExpedition(null);const params=new URLSearchParams(window.location.search);params.delete('compose');history.replaceState(null,'',`${window.location.pathname}?${params}`)}
  const saveExpedition=async()=>{if(!expedition)return;setBusy(true);try{await api.createRecord(data.campaign.id,{kind:'scene',title:`Expedició: ${expedition.temple.name}`,status:'planned',visibility:'dm',data:{description:`${expedition.situation.summary} ${expedition.temple.summary}`,terrain:terrain||'jungle',level,difficulty:difficulty||undefined,homebrew_kit:Object.fromEntries(categories.map(kind=>[kind,{id:expedition[kind].id,name:expedition[kind].name,summary:expedition[kind].summary,data:expedition[kind].data}]))}});await api.addActivity(data.campaign.id,{kind:'planning',title:`Expedició preparada: ${expedition.temple.name}`,details:`${expedition.enemy.name} · ${expedition.situation.name} · ${expedition.minigame.name}`,visibility:'dm'});setNotice('Expedició desada com una escena completa al planificador.');closeExpedition();changed()}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut desar l’expedició')}finally{setBusy(false)}}

  const importPack=async()=>{if(!packFile)return;setBusy(true);setError('');try{const imported=await api.importHomebrewPack(packFile);setNotice(`${imported.name} importat amb ${imported.item_count} recursos.`);setPackFile(null);setPackId(imported.id);await refreshPacks()}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut importar el pack')}finally{setBusy(false)}}
  const removePack=async(pack:HomebrewPack)=>{if(pack.bundled||!confirm(`Eliminar el pack local “${pack.name}”?`))return;setBusy(true);try{await api.deleteHomebrewPack(pack.id);if(packId===pack.id)setPackId('');await refreshPacks();setNotice(`${pack.name} eliminat. La campanya aplicada no s’ha modificat.`)}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut eliminar el pack')}finally{setBusy(false)}}
  const addEnemy=async()=>{if(!selected)return;setBusy(true);try{let target=data.combats.find(item=>item.id===combatId);if(!target){target=await api.createCombat(data.campaign.id,`Trobada: ${selected.name}`);setCombatId(target.id)}const actions=asObjects(selected.data.actions).map(item=>({name:text(item.name,'Acció'),description:text(item.description),source:selected.pack_name}));for(let index=0;index<quantity;index++){await api.addCombatant(target.id,{name:`${selected.name}${quantity>1?` ${index+1}`:''}`,kind:'enemy',initiative:10+number(selected.data.initiative_bonus)-index,initiative_bonus:number(selected.data.initiative_bonus),armor_class:number(selected.data.armor_class,10),max_hp:number(selected.data.hit_points,1),actions,notes:`CR ${number(selected.data.challenge_rating)} · ${text(selected.data.tactics)}`,reference_id:selected.id})}setNotice(`${quantity} × ${selected.name} afegit al combat ${target.name}.`);changed()}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut afegir al combat')}finally{setBusy(false)}}
  const prepareScene=async()=>{if(!selected)return;setBusy(true);try{await api.createRecord(data.campaign.id,{kind:'scene',title:selected.name,status:'planned',visibility:'dm',data:{pack_item_id:selected.id,pack_id:selected.pack_id,category:selected.category,description:selected.summary,terrains:selected.terrains,...selected.data}});setNotice(`${selected.name} s’ha afegit al planificador com a escena.`);changed()}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut preparar l’escena')}finally{setBusy(false)}}
  const prepareMinigame=async()=>{if(!selected)return;setBusy(true);try{const record=await api.createRecord(data.campaign.id,{kind:'clock',title:selected.name,status:'active',visibility:'dm',data:{pack_item_id:selected.id,pack_id:selected.pack_id,description:selected.summary,current:0,maximum:number(selected.data.target,4),danger:0,danger_max:number(selected.data.danger_max,3),round:1,round_limit:number(selected.data.round_limit,5),checks:selected.data.checks,twists:selected.data.twists,success:selected.data.success,consequence:selected.data.failure}});await api.createRecord(data.campaign.id,{kind:'scene',title:`Escena: ${selected.name}`,status:'planned',visibility:'dm',linked_id:record.id,data:{pack_item_id:selected.id,description:text(selected.data.setup),checks:selected.data.checks,twists:selected.data.twists}});setNotice('Minijoc preparat com a clock i escena de sessió.');changed()}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut preparar el minijoc')}finally{setBusy(false)}}
  const playCheck=async(option:CheckOption)=>{if(!preparedClock)return;setBusy(true);setError('');try{const notation=`1d20${modifier===0?'':modifier>0?`+${modifier}`:modifier}`;const roll=await api.rollDice(data.campaign.id,{notation,label:`${selected?.name} · ${option.name}`,actor:option.ability,mode:'normal',dc:option.dc});const nextCurrent=Math.min(maximum,current+(roll.success?1:0));const nextDanger=Math.min(dangerMax,danger+(roll.success?0:1));const nextRound=round+1;const status=nextCurrent>=maximum?'completed':nextDanger>=dangerMax||nextRound>roundLimit?'failed':'active';await api.updateRecord(preparedClock.id,{status,data:{...clockData,current:nextCurrent,danger:nextDanger,round:nextRound,last_roll:roll.total,last_check:option.name}});await api.addActivity(data.campaign.id,{kind:'minigame',title:`${selected?.name}: ${roll.success?'èxit':'fallada'}`,details:`${option.name}: ${roll.total} contra CD ${option.dc}`,linked_id:preparedClock.id,visibility:'dm'});setNotice(`${option.name}: ${roll.total} · ${roll.success?'+1 progrés':'+1 perill'}`);changed()}catch(exception){setError(exception instanceof Error?exception.message:'No s’ha pogut resoldre la prova')}finally{setBusy(false)}}

  return <div className="studio-page jungle-toolkit">
    <div className="studio-heading"><div><span className="eyebrow">{packs.filter(pack=>pack.status==='ready').length} packs · {resourceCount||34} recursos</span><h1>Laboratori d’aventures de la selva</h1><p>Construeix escenes coherents i aplica-les a campanya sense perdre el control del DM.</p></div><div className="jungle-heading-actions"><button onClick={()=>void generateExpedition()} disabled={busy}><Sparkles/> Compondre expedició</button><Landmark/></div></div>
    {notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<X/></div>}{error&&<div className="alert dismissible" onClick={()=>setError('')}>{error}<X/></div>}
    <div className="brew-tabs">{categories.map(item=><button className={category===item?'active':''} onClick={()=>changeCategory(item)} key={item}>{item==='enemy'?<Skull/>:item==='temple'?<Landmark/>:item==='situation'?<Leaf/>:<Play/>}<span>{categoryLabels[item]}</span></button>)}</div>
    <section className="brew-filters"><div className="brew-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')void load()}} placeholder="Cerca per nom, tema o etiqueta…"/><button onClick={()=>void load()}>Cercar</button></div><label>Pack<select value={packId} onChange={event=>setPackId(event.target.value)}><option value="">Tots</option>{packs.filter(pack=>pack.status==='ready').map(pack=><option value={pack.id} key={pack.id}>{pack.name}</option>)}</select></label><label>Terreny<select value={terrain} onChange={event=>setTerrain(event.target.value)}><option value="">Qualsevol</option>{Object.entries(terrainLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Nivell <b>{level}</b><input type="range" min="1" max="20" value={level} onChange={event=>setLevel(Number(event.target.value))}/></label><label>Dificultat<select value={difficulty} onChange={event=>setDifficulty(Number(event.target.value))}><option value="0">Qualsevol</option>{[1,2,3,4,5].map(item=><option value={item} key={item}>{item}/5</option>)}</select></label><button className={`favorite-filter ${favoriteOnly?'active':''}`} onClick={()=>setFavoriteOnly(value=>!value)}><Star fill={favoriteOnly?'currentColor':'none'}/> {favorites.length}</button><button className="random-brew" disabled={!visibleItems.length} onClick={randomItem}><Shuffle/> Sorprèn-me</button></section>
    <details className="pack-manager"><summary><Package/> Gestionar packs locals <small>JSON validat · màxim 1 MB</small></summary><div className="pack-manager-body"><div className="pack-upload"><FolderUp/><div><strong>Importar un pack propi</strong><small>Es desa només a data/homebrew_packs i no puja a Git.</small></div><input type="file" accept=".json,application/json" onChange={event=>setPackFile(event.target.files?.[0]??null)}/><button disabled={!packFile||busy} onClick={()=>void importPack()}>Validar i importar</button></div><div className="pack-list">{packs.map(pack=><article className={pack.status} key={pack.id}><Package/><span><strong>{pack.name}</strong><small>{pack.status==='ready'?`${pack.item_count} recursos · v${pack.version} · ${pack.license}`:pack.error}</small></span>{pack.bundled?<em>Inclòs</em>:<button className="icon-button danger" onClick={()=>void removePack(pack)}><Trash2/></button>}</article>)}</div></div></details>
    <div className="brew-layout"><section className="brew-list">{visibleItems.map(item=><button className={selected?.id===item.id?'active':''} key={item.id} onClick={()=>choose(item)}><div><span>{item.tags.slice(0,3).join(' · ')}</span><strong>{item.name}</strong><small>Nivells {item.min_level}–{item.max_level} · dificultat {item.difficulty}/5</small></div><Star className="item-favorite" fill={favorites.includes(item.id)?'currentColor':'none'} onClick={event=>{event.stopPropagation();toggleFavorite(item.id)}}/><ChevronRight/></button>)}{!visibleItems.length&&!busy&&<p>{favoriteOnly?'Cap favorit coincideix amb aquests filtres.':'No hi ha resultats amb aquests filtres.'}</p>}</section><section className="studio-card brew-detail">{selected?<><header><div><span className="eyebrow">{categoryLabels[selected.category]} · {selected.terrains.map(item=>terrainLabels[item]??item).join(', ')}</span><h2>{selected.name}</h2><p>{selected.summary}</p><small className="pack-origin">{selected.pack_name}</small></div><button className={`favorite-detail ${favorites.includes(selected.id)?'active':''}`} onClick={()=>toggleFavorite(selected.id)} title="Desar com a favorit"><Star fill={favorites.includes(selected.id)?'currentColor':'none'}/></button><b className="difficulty-seal">{selected.difficulty}<small>/5</small></b></header><BrewContent item={selected}/>{selected.category==='enemy'&&<><EncounterBudget item={selected} quantity={quantity} party={data.party}/><div className="brew-action"><select value={combatId} onChange={event=>setCombatId(event.target.value)}><option value="">Crear combat nou</option>{data.combats.map(item=><option value={item.id} key={item.id}>{item.name} · {item.status}</option>)}</select><label>Quantitat<input type="number" min="1" max="12" value={quantity} onChange={event=>setQuantity(Math.max(1,Math.min(12,Number(event.target.value))))}/></label><button className="primary" disabled={busy} onClick={()=>void addEnemy()}><Swords/> Afegir al combat</button></div></>}{(selected.category==='temple'||selected.category==='situation')&&<div className="brew-action single"><button className="primary" disabled={busy} onClick={()=>void prepareScene()}><Plus/> Preparar com a escena</button></div>}{selected.category==='minigame'&&<div className="brew-action single">{preparedClock?<MinigameRunner record={preparedClock} current={current} maximum={maximum} danger={danger} dangerMax={dangerMax} round={round} roundLimit={roundLimit} checks={checks} checkIndex={checkIndex} setCheckIndex={setCheckIndex} modifier={modifier} setModifier={setModifier} play={playCheck} busy={busy}/>:<button className="primary" disabled={busy} onClick={()=>void prepareMinigame()}><Sparkles/> Preparar minijoc persistent</button>}</div>}<footer>Homebrew identificat · adaptable abans d’aplicar · dades locals</footer></>:<div className="empty"><Landmark/><p>Selecciona un recurs.</p></div>}</section></div>
    {expedition&&<ExpeditionModal kit={expedition} close={closeExpedition} regenerate={generateExpedition} save={saveExpedition} busy={busy}/>}
  </div>
}

function EncounterBudget({item,quantity,party}:{item:HomebrewItem;quantity:number;party:PartySettings}){
  const thresholds=xpThresholds[Math.max(0,Math.min(19,party.level-1))].map(value=>value*party.size)
  const baseIndex=quantity===1?1:quantity===2?2:quantity<=6?3:quantity<=10?4:quantity<=14?5:6
  const multiplierIndex=Math.max(0,Math.min(7,baseIndex+(party.size<3?1:party.size>=6?-1:0)))
  const multiplier=[0.5,1,1.5,2,2.5,3,4,5][multiplierIndex]
  const raw=number(item.data.xp)*quantity;const adjusted=Math.round(raw*multiplier)
  const label=adjusted>=thresholds[3]*1.5?'Extrema':adjusted>=thresholds[3]?'Mortal':adjusted>=thresholds[2]?'Difícil':adjusted>=thresholds[1]?'Mitjana':adjusted>=thresholds[0]?'Fàcil':'Trivial'
  const tone=label==='Mortal'||label==='Extrema'?'danger':label==='Difícil'?'warning':'safe'
  const width=Math.min(100,adjusted/Math.max(1,thresholds[3]*1.5)*100)
  return <section className={`encounter-budget ${tone}`}><header><div><span>Estimació Basic Rules 2014</span><strong>{label}</strong></div><b>{adjusted.toLocaleString()} XP ajustats</b></header><div className="budget-bar"><i style={{width:`${width}%`}}/></div><div className="budget-thresholds"><span>Fàcil <b>{thresholds[0]}</b></span><span>Mitjana <b>{thresholds[1]}</b></span><span>Difícil <b>{thresholds[2]}</b></span><span>Mortal <b>{thresholds[3]}</b></span></div><p>{quantity} × {number(item.data.xp)} XP = {raw} XP; multiplicador ×{multiplier} per nombre d’enemics{party.size<3?' i grup petit':party.size>=6?' i grup gran':''}.{number(item.data.challenge_rating)>party.level?' Atenció: el CR supera el nivell mitjà del grup.':''}</p></section>
}

function ExpeditionModal({kit,close,regenerate,save,busy}:{kit:ExpeditionKit;close:()=>void;regenerate:()=>Promise<void>;save:()=>Promise<void>;busy:boolean}){
  return <div className="drawer-overlay" onMouseDown={close}><section className="modal expedition-modal" onMouseDown={event=>event.stopPropagation()}><button className="icon-button close" onClick={close}><X/></button><span className="eyebrow">Compositor procedural</span><h2>Expedició preparada</h2><p className="muted">Quatre peces compatibles que pots revisar abans de convertir-les en una escena persistent.</p><div className="expedition-flow">{categories.map((category,index)=><article key={category}><span>{index+1}</span><div><small>{categoryLabels[category]}</small><strong>{kit[category].name}</strong><p>{kit[category].summary}</p></div></article>)}</div><div className="expedition-actions"><button disabled={busy} onClick={()=>void regenerate()}><RotateCcw/> Regenerar</button><button className="primary" disabled={busy} onClick={()=>void save()}><Plus/> Desar al planificador</button></div></section></div>
}

function BrewContent({item}:{item:HomebrewItem}){
  const traits=Array.isArray(item.data.traits)?item.data.traits.map(String):[];const actions=asObjects(item.data.actions);const rooms=asObjects(item.data.rooms);const choices=asObjects(item.data.choices);const checks=asObjects(item.data.checks);const twists=Array.isArray(item.data.twists)?item.data.twists.map(String):[]
  if(item.category==='enemy')return <div className="brew-content"><div className="brew-stats"><span>CA <b>{number(item.data.armor_class)}</b></span><span>PG <b>{number(item.data.hit_points)}</b></span><span>CR <b>{number(item.data.challenge_rating)}</b></span><span>XP <b>{number(item.data.xp)}</b></span></div><h3>Trets</h3>{traits.map(line=><p key={line}>{line}</p>)}<h3>Accions</h3>{actions.map((action,index)=><article key={index}><strong>{text(action.name)}</strong><p>{text(action.description)}</p></article>)}<details><summary>Tàctica i recuperació</summary><p>{text(item.data.tactics)}</p><p><b>Recuperable:</b> {text(item.data.salvage)}</p></details></div>
  if(item.category==='temple')return <div className="brew-content"><div className="brew-callout"><b>Ganxo</b><p>{text(item.data.hook)}</p></div><p><b>Aproximació:</b> {text(item.data.approach)}</p><h3>Sales modulars</h3><div className="room-list">{rooms.map((room,index)=><article key={index}><span>{index+1}</span><div><strong>{text(room.name)}</strong><p>{text(room.challenge)}</p></div></article>)}</div><details open><summary>Secret, guardià i recompensa</summary><p><b>Guardià:</b> {text(item.data.guardian)}</p><p><b>Secret:</b> {text(item.data.secret)}</p><p><b>Recompensa:</b> {text(item.data.reward)}</p><p><b>Escalada:</b> {text(item.data.escalation)}</p></details></div>
  if(item.category==='situation')return <div className="brew-content"><div className="brew-callout"><b>Situació inicial</b><p>{text(item.data.prompt)}</p></div><div className="choice-list">{choices.map((choice,index)=><article key={index}><strong>{text(choice.label)}</strong><span>{text(choice.check)}{number(choice.dc)>0?` · CD ${number(choice.dc)}`:''}</span><p><Check/> {text(choice.success)}</p><p><X/> {text(choice.failure)}</p></article>)}</div><details><summary>Gir i continuació</summary><p><b>Gir:</b> {text(item.data.twist)}</p><p><b>Després:</b> {text(item.data.follow_up)}</p></details></div>
  return <div className="brew-content"><div className="brew-callout"><b>Funcionament</b><p>{text(item.data.setup)}</p></div><div className="minigame-summary"><span>{number(item.data.target)} progrés</span><span>{number(item.data.danger_max)} perill</span><span>{number(item.data.round_limit)} rondes</span></div><h3>Proves suggerides</h3>{checks.map((check,index)=><article key={index}><strong>{text(check.name)}</strong><p>{text(check.ability)} · CD {number(check.dc)}</p></article>)}<details><summary>Girs i desenllaç</summary>{twists.map(line=><p key={line}>• {line}</p>)}<p><b>Èxit:</b> {text(item.data.success)}</p><p><b>Fallada:</b> {text(item.data.failure)}</p></details></div>
}

function MinigameRunner({record,current,maximum,danger,dangerMax,round,roundLimit,checks,checkIndex,setCheckIndex,modifier,setModifier,play,busy}:{record:CampaignRecord;current:number;maximum:number;danger:number;dangerMax:number;round:number;roundLimit:number;checks:CheckOption[];checkIndex:number;setCheckIndex:(value:number)=>void;modifier:number;setModifier:(value:number)=>void;play:(option:CheckOption)=>Promise<void>;busy:boolean}){
  const safeIndex=checks[checkIndex]?checkIndex:0;const option=checks[safeIndex]
  return <div className="minigame-runner"><header><div><span>Clock actiu</span><strong>{record.title}</strong></div><em>Ronda {round}/{roundLimit}</em></header><div className="clock-track"><label>Progrés <b>{current}/{maximum}</b><i><span style={{width:`${current/maximum*100}%`}}/></i></label><label>Perill <b>{danger}/{dangerMax}</b><i className="danger"><span style={{width:`${danger/dangerMax*100}%`}}/></i></label></div><div className="check-controls"><select value={safeIndex} onChange={event=>setCheckIndex(Number(event.target.value))}>{checks.map((item,index)=><option value={index} key={`${item.name}-${index}`}>{item.name} · CD {item.dc}</option>)}</select><label>Mod.<input type="number" min="-10" max="20" value={modifier} onChange={event=>setModifier(Number(event.target.value))}/></label><button disabled={busy||!option} onClick={()=>option&&void play(option)}><Dices/> Tirar prova</button></div></div>
}
