import { useMemo, useState } from 'react'
import { BookOpen, CalendarDays, Check, Clock3, Flag, Map, Play, Plus, ScrollText, Trash2 } from 'lucide-react'
import { api } from './api'
import type { CampaignRecord, Dashboard } from './types'

type Tab='planner'|'quests'|'calendar'|'clocks'|'timeline'|'maps'|'links'
const statusLabels:Record<string,string>={unknown:'Desconeguda',available:'Disponible',active:'Activa',completed:'Completada',failed:'Fallida',planned:'Preparada',used:'Utilitzada',delayed:'Ajornada'}
const value=(data:Record<string,unknown>,key:string,fallback='')=>String(data[key]??fallback)

export function OperationsStudio({data,changed}:{data:Dashboard;changed:()=>void}){
  const [tab,setTab]=useState<Tab>('planner');const [,setBusy]=useState(false);const [error,setError]=useState('')
  const [form,setForm]=useState({title:'',description:'',visibility:'dm',due_day:data.campaign.current_day+1,maximum:4,location_id:'',source_id:'',x:50,y:50})
  const [note,setNote]=useState('');const [selectedMap,setSelectedMap]=useState('')
  const records=(kind:string)=>data.campaign_records.filter(x=>x.kind===kind)
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();changed()}catch(e){setError(e instanceof Error?e.message:'No s’ha pogut completar')}finally{setBusy(false)}}
  const create=(kind:CampaignRecord['kind'],extra:Record<string,unknown>={})=>run(async()=>{await api.createRecord(data.campaign.id,{kind,title:form.title,status:kind==='scene'?'planned':'active',visibility:form.visibility,due_day:['calendar','quest'].includes(kind)?form.due_day:null,data:{description:form.description,...extra}});setForm({...form,title:'',description:''})})
  const setStatus=(item:CampaignRecord,status:string)=>run(()=>api.updateRecord(item.id,{status}))
  const activeSession=data.sessions.find(x=>!x.ended_at)
  const upcoming=records('calendar').filter(x=>x.status==='active'&&(x.due_day??999999)<=data.campaign.current_day+7)
  const threats=records('clock').filter(x=>x.status!=='completed')
  const maps=records('map');const map=maps.find(x=>x.id===selectedMap)??maps[0]
  const markers=records('marker').filter(x=>x.linked_id===map?.id)
  const imageSource=map?value(map.data,'source_id'):''
  const totalRisk=useMemo(()=>data.hex_cells.reduce((sum,x)=>sum+x.risk_level+x.alert_level,0),[data.hex_cells])
  return <div className="operations-studio"><div className="studio-heading"><div><span className="eyebrow">Campaign Operations · v0.9</span><h1>Preparació i continuïtat</h1><p>Missions, temps, amenaces, escenes i crònica connectades a la partida.</p></div><ScrollText/></div>
    <div className="ops-kpis"><span><Flag/><b>{records('quest').filter(x=>x.status==='active').length}</b> missions actives</span><span><CalendarDays/><b>{upcoming.length}</b> venciments propers</span><span><Clock3/><b>{threats.length}</b> amenaces</span><span><Map/><b>{totalRisk}</b> risc + alerta</span></div>
    <nav className="tool-tabs"><button className={tab==='planner'?'active':''} onClick={()=>setTab('planner')}><Play/>Planificador</button><button className={tab==='quests'?'active':''} onClick={()=>setTab('quests')}><Flag/>Missions</button><button className={tab==='calendar'?'active':''} onClick={()=>setTab('calendar')}><CalendarDays/>Calendari</button><button className={tab==='clocks'?'active':''} onClick={()=>setTab('clocks')}><Clock3/>Clocks</button><button className={tab==='timeline'?'active':''} onClick={()=>setTab('timeline')}><ScrollText/>Cronologia</button><button className={tab==='maps'?'active':''} onClick={()=>setTab('maps')}><Map/>Mapes</button><button className={tab==='links'?'active':''} onClick={()=>setTab('links')}><BookOpen/>Fonts</button></nav>{error&&<div className="alert">{error}</div>}

    {tab==='planner'&&<div className="ops-layout"><main><section className="studio-card session-brief"><header><div><span className="eyebrow">Sessió {activeSession?'en curs':'per preparar'}</span><h2>Taula de direcció</h2></div>{!activeSession?<button className="primary" onClick={()=>run(()=>api.startSession(data.campaign.id))}><Play/> Iniciar sessió</button>:<button onClick={()=>run(()=>api.closeSession(activeSession.id))}><Check/> Tancar i resumir</button>}</header><div className="brief-grid"><Brief title="Escenes preparades" items={records('scene').filter(x=>x.status==='planned')}/><Brief title="Missions obertes" items={records('quest').filter(x=>['active','available'].includes(x.status))}/><Brief title="Calendari pròxim" items={upcoming}/><Brief title="Amenaces" items={threats}/><Brief title="Encounters pendents" items={data.encounters.filter(x=>x.status!=='resolved').map(x=>({id:x.id,title:x.title,status:x.encounter_type}))}/><Brief title="Botí pendent" items={data.rewards.filter(x=>!x.claimed).map(x=>({id:x.id,title:x.title,status:x.tier}))}/></div></section><section className="scene-list">{records('scene').map(item=><RecordCard key={item.id} item={item} remove={()=>run(()=>api.deleteRecord(item.id))} status={s=>setStatus(item,s)}/>)}</section></main><RecordForm title="Preparar una escena" submit={()=>create('scene',{location_id:form.location_id,notes:form.description})} form={form} setForm={setForm} data={data}/></div>}

    {tab==='quests'&&<div className="ops-layout"><main className="record-grid">{records('quest').map(item=><RecordCard key={item.id} item={item} remove={()=>run(()=>api.deleteRecord(item.id))} status={s=>setStatus(item,s)}/>)}</main><RecordForm title="Nova missió" submit={()=>create('quest',{objectives:form.description.split('\n').filter(Boolean),reward:'',progress:0})} form={form} setForm={setForm} data={data} due/></div>}
    {tab==='calendar'&&<div className="ops-layout"><main className="calendar-line">{records('calendar').map(item=><article className={(item.due_day??0)<data.campaign.current_day?'overdue':''} key={item.id}><b>Dia {item.due_day}</b><span><strong>{item.title}</strong><small>{value(item.data,'description')}</small></span><select value={item.status} onChange={e=>setStatus(item,e.target.value)}><option value="active">Pendent</option><option value="completed">Completat</option><option value="failed">Vençut</option></select><button className="icon-button danger" onClick={()=>run(()=>api.deleteRecord(item.id))}><Trash2/></button></article>)}</main><RecordForm title="Nou esdeveniment" submit={()=>create('calendar')} form={form} setForm={setForm} data={data} due/></div>}
    {tab==='clocks'&&<div className="ops-layout"><main className="clock-grid">{records('clock').map(item=>{const current=Number(item.data.current??0),maximum=Number(item.data.maximum??4);return <article key={item.id}><header><span><strong>{item.title}</strong><small>{value(item.data,'description')}</small></span><b>{current}/{maximum}</b></header><div className="clock-segments">{Array.from({length:maximum},(_,i)=><i className={i<current?'filled':''} key={i}/>)}</div><p>{value(item.data,'consequence','Sense conseqüència definida')}</p><div><button disabled={current<=0} onClick={()=>run(()=>api.updateRecord(item.id,{data:{...item.data,current:current-1}}))}>−</button><button disabled={current>=maximum} onClick={()=>run(()=>api.updateRecord(item.id,{data:{...item.data,current:current+1},status:current+1>=maximum?'completed':item.status}))}>+</button><button className="icon-button danger" onClick={()=>run(()=>api.deleteRecord(item.id))}><Trash2/></button></div></article>})}</main><RecordForm title="Nou clock" submit={()=>create('clock',{current:0,maximum:form.maximum,consequence:form.description})} form={form} setForm={setForm} data={data} maximum/></div>}
    {tab==='timeline'&&<div className="ops-layout"><main className="timeline-list">{data.campaign_activities.map(item=><article key={item.id}><i/><span><small>{new Date(item.created_at).toLocaleString()} · {item.kind} · {item.visibility==='players'?'jugadors':'DM'}</small><strong>{item.title}</strong>{item.details&&<p>{item.details}</p>}</span></article>)}</main><aside className="studio-card quick-note"><h3>Nota ràpida</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Què ha passat?"/><div className="button-row"><button disabled={note.trim().length<2} onClick={()=>run(async()=>{await api.addActivity(data.campaign.id,{title:note,kind:'note',visibility:'dm'});setNote('')})}>Només DM</button><button className="primary" disabled={note.trim().length<2} onClick={()=>run(async()=>{await api.addActivity(data.campaign.id,{title:note,kind:'note',visibility:'players'});setNote('')})}>Compartir</button></div></aside></div>}
    {tab==='maps'&&<div className="ops-layout"><main><div className="map-selector">{maps.map(item=><button className={map?.id===item.id?'active':''} onClick={()=>setSelectedMap(item.id)} key={item.id}>{item.title}</button>)}</div>{map?<section className="image-map" style={imageSource?{backgroundImage:`linear-gradient(#07100d55,#07100d55),url(/api/library/${imageSource}/asset)`}:{}}>{markers.map(marker=><button style={{left:`${Number(marker.data.x??50)}%`,top:`${Number(marker.data.y??50)}%`}} key={marker.id} title={value(marker.data,'notes')}><Map/><span>{marker.title}</span></button>)}</section>:<div className="empty-state">Crea un mapa i vincula-hi una imatge de la biblioteca.</div>}</main><aside className="party-side"><div className="studio-card"><h3>Nou mapa</h3><label>Nom<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Imatge de biblioteca<select value={form.source_id} onChange={e=>setForm({...form,source_id:e.target.value})}><option value="">Fons abstracte</option>{data.sources.filter(x=>x.asset_kind==='map'||x.asset_kind==='image').map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><button className="primary full" disabled={form.title.length<2} onClick={()=>create('map',{source_id:form.source_id})}>Crear mapa</button></div>{map&&<div className="studio-card"><h3>Nou marcador</h3><label>Títol<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="two-columns"><label>X %<input type="number" min="0" max="100" value={form.x} onChange={e=>setForm({...form,x:Number(e.target.value)})}/></label><label>Y %<input type="number" min="0" max="100" value={form.y} onChange={e=>setForm({...form,y:Number(e.target.value)})}/></label></div><label>Visibilitat<select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="dm">Només DM</option><option value="players">Jugadors</option></select></label><button disabled={form.description.length<2} onClick={()=>run(()=>api.createRecord(data.campaign.id,{kind:'marker',title:form.description,visibility:form.visibility,linked_id:map.id,data:{x:form.x,y:form.y,notes:''}}))}>Afegir marcador</button></div>}</aside></div>}
    {tab==='links'&&<div className="ops-layout"><main className="record-grid">{records('library_link').map(item=><RecordCard key={item.id} item={item} remove={()=>run(()=>api.deleteRecord(item.id))} status={s=>setStatus(item,s)}/>)}</main><aside className="studio-card record-form"><h3><BookOpen/> Vincular document</h3><label>Nom del vincle<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Document<select value={form.source_id} onChange={e=>setForm({...form,source_id:e.target.value})}><option value="">Tria una font</option>{data.sources.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Element relacionat<select value={form.location_id} onChange={e=>setForm({...form,location_id:e.target.value})}><option value="">Campanya general</option>{data.campaign_records.filter(x=>['quest','scene','map'].includes(x.kind)).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Pàgina / nota<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="primary full" disabled={form.title.length<2||!form.source_id} onClick={()=>create('library_link',{source_id:form.source_id,target_id:form.location_id,note:form.description})}>Crear vincle</button></aside></div>}
  </div>
}

function Brief({title,items}:{title:string;items:Array<{id:string;title:string;status:string}>}){return <section><h3>{title}<b>{items.length}</b></h3>{items.slice(0,5).map(x=><p key={x.id}><span>{x.title}</span><small>{statusLabels[x.status]??x.status}</small></p>)}{!items.length&&<em>Res pendent</em>}</section>}
function RecordCard({item,remove,status}:{item:CampaignRecord;remove:()=>void;status:(value:string)=>void}){return <article className="record-card"><header><span className={`visibility ${item.visibility}`}>{item.visibility}</span>{item.due_day&&<small>Dia {item.due_day}</small>}<button className="icon-button danger" onClick={remove}><Trash2/></button></header><h3>{item.title}</h3><p>{value(item.data,'description')||value(item.data,'notes')}</p><footer><select value={item.status} onChange={e=>status(e.target.value)}><option value="unknown">Desconeguda</option><option value="available">Disponible</option><option value="active">Activa</option><option value="planned">Preparada</option><option value="used">Utilitzada</option><option value="delayed">Ajornada</option><option value="completed">Completada</option><option value="failed">Fallida</option></select></footer></article>}
function RecordForm({title,submit,form,setForm,data,due=false,maximum=false}:{title:string;submit:()=>void;form:{title:string;description:string;visibility:string;due_day:number;maximum:number;location_id:string;source_id:string;x:number;y:number};setForm:(value:typeof form)=>void;data:Dashboard;due?:boolean;maximum?:boolean}){return <aside className="studio-card record-form"><h3><Plus/> {title}</h3><label>Títol<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Descripció / punts<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{due&&<label>Dia límit<input type="number" min="1" value={form.due_day} onChange={e=>setForm({...form,due_day:Number(e.target.value)})}/></label>}{maximum&&<label>Segments<input type="number" min="2" max="12" value={form.maximum} onChange={e=>setForm({...form,maximum:Number(e.target.value)})}/></label>}<label>Ubicació<select value={form.location_id} onChange={e=>setForm({...form,location_id:e.target.value})}><option value="">Sense vincle</option>{data.locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Visibilitat<select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="dm">Només DM</option><option value="players">Jugadors</option><option value="world">Estat del món</option></select></label><button className="primary full" disabled={form.title.trim().length<2} onClick={submit}><Plus/> Crear</button></aside>}
