import { useState } from 'react'
import { Backpack, Coins, Heart, History, Plus, Shield, Swords, Trash2, Users } from 'lucide-react'
import { api } from './api'
import type { Character, Dashboard, InventoryItem, Treasury } from './types'

type Tab='characters'|'inventory'|'treasury'|'history'
const abilities:Record<string,string>={str:'FOR',dex:'DES',con:'CON',int:'INT',wis:'SAV',cha:'CAR'}
const currencies:(keyof Pick<Treasury,'cp'|'sp'|'ep'|'gp'|'pp'>)[]=['cp','sp','ep','gp','pp']

export function PartyManager({data,changed}:{data:Dashboard;changed:()=>void}){
  const [tab,setTab]=useState<Tab>('characters')
  const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const [charForm,setCharForm]=useState({name:'',player_name:'',class_name:'Aventurer',ancestry:'',level:data.party.level,armor_class:14,max_hp:20})
  const [itemForm,setItemForm]=useState({name:'',category:'gear',quantity:1,weight:0,value:0,owner_type:'party',owner_id:'',consumable:false})
  const [currency,setCurrency]=useState('gp');const [amount,setAmount]=useState(0);const [reason,setReason]=useState('Ajust manual')
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();changed()}catch(e){setError(e instanceof Error?e.message:'No s’ha pogut completar')}finally{setBusy(false)}}
  const hp=(character:Character,delta:number)=>run(()=>api.updateCharacter(character.id,{current_hp:Math.max(0,Math.min(character.max_hp,character.current_hp+delta))}))
  const transfer=(item:InventoryItem,value:string)=>{const [owner_type,owner_id]=value.split(':');return run(()=>api.updateInventory(item.id,{owner_type:owner_type as InventoryItem['owner_type'],owner_id:owner_id||undefined,equipped:false}))}
  const activeCombat=data.combats.find(x=>x.status==='active')
  return <section className="party-studio">
    <div className="tool-title"><div className="party-mark"><Users/><Backpack/></div><div><span className="eyebrow">Party Core · v0.8</span><h1>Grup, inventari i tresoreria</h1><p>Una única font de veritat per als personatges, el botí i els recursos de la campanya.</p></div></div>
    <nav className="tool-tabs">
      <button className={tab==='characters'?'active':''} onClick={()=>setTab('characters')}><Users/> Personatges <b>{data.characters.length}</b></button>
      <button className={tab==='inventory'?'active':''} onClick={()=>setTab('inventory')}><Backpack/> Inventari <b>{data.inventory.length}</b></button>
      <button className={tab==='treasury'?'active':''} onClick={()=>setTab('treasury')}><Coins/> Tresoreria</button>
      <button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History/> Historial</button>
    </nav>
    {error&&<div className="alert">{error}</div>}

    {tab==='characters'&&<div className="party-layout">
      <div className="character-grid">{data.characters.map(character=><article className={`character-card ${character.active?'':'inactive'}`} key={character.id}>
        <header><div className="character-avatar">{character.name.slice(0,2).toUpperCase()}</div><span><strong>{character.name}</strong><small>{character.ancestry} {character.class_name} · nivell {character.level}{character.player_name&&` · ${character.player_name}`}</small></span><button className="icon-button danger" title="Eliminar" onClick={()=>confirm(`Eliminar ${character.name}?`)&&run(()=>api.deleteCharacter(character.id))}><Trash2/></button></header>
        <div className="character-vitals"><span><Shield/> CA <b>{character.armor_class}</b></span><span><Heart/> PG <b>{character.current_hp}/{character.max_hp}</b>{character.temp_hp>0&&<em>+{character.temp_hp}</em>}</span><span>Passiva <b>{character.passive_perception}</b></span></div>
        <div className="hp-track"><i style={{width:`${Math.max(0,character.current_hp/character.max_hp*100)}%`}}/></div>
        <div className="quick-hp"><button disabled={busy} onClick={()=>hp(character,-5)}>-5</button><button disabled={busy} onClick={()=>hp(character,-1)}>-1</button><button disabled={busy} onClick={()=>hp(character,1)}>+1</button><button disabled={busy} onClick={()=>hp(character,5)}>+5</button><button onClick={()=>run(()=>api.updateCharacter(character.id,{current_hp:character.max_hp,temp_hp:0}))}>Màxim</button></div>
        <div className="ability-row">{Object.entries(abilities).map(([key,label])=>{const score=character.ability_scores[key]??10;const mod=Math.floor((score-10)/2);return <span key={key}>{label}<b>{score}</b><small>{mod>=0?'+':''}{mod}</small></span>})}</div>
        <details className="advanced-fold"><summary>Recursos, estats i fitxa</summary><div className="tag-row">{character.conditions.map(x=><i key={x}>{x}</i>)}{character.exhaustion>0&&<i>Esgotament {character.exhaustion}</i>}{!character.conditions.length&&!character.exhaustion&&<small>Sense estats negatius</small>}</div>{character.resources.map(resource=><p key={resource.name}>{resource.name}: <b>{resource.current}/{resource.maximum}</b> · descans {resource.reset==='short'?'curt':'llarg'}</p>)}<label className="toggle-inline"><input type="checkbox" checked={character.share_with_players} onChange={e=>run(()=>api.updateCharacter(character.id,{share_with_players:e.target.checked}))}/> Visible per als jugadors</label></details>
      </article>)}</div>
      <aside className="party-side"><div className="studio-card"><h3><Plus/> Nou personatge</h3><label>Nom<input value={charForm.name} onChange={e=>setCharForm({...charForm,name:e.target.value})}/></label><div className="two-columns"><label>Jugador<input value={charForm.player_name} onChange={e=>setCharForm({...charForm,player_name:e.target.value})}/></label><label>Classe<input value={charForm.class_name} onChange={e=>setCharForm({...charForm,class_name:e.target.value})}/></label><label>Llinatge<input value={charForm.ancestry} onChange={e=>setCharForm({...charForm,ancestry:e.target.value})}/></label><label>Nivell<input type="number" min="1" max="20" value={charForm.level} onChange={e=>setCharForm({...charForm,level:Number(e.target.value)})}/></label><label>CA<input type="number" value={charForm.armor_class} onChange={e=>setCharForm({...charForm,armor_class:Number(e.target.value)})}/></label><label>PG màxims<input type="number" value={charForm.max_hp} onChange={e=>setCharForm({...charForm,max_hp:Number(e.target.value)})}/></label></div><button className="primary full" disabled={busy||charForm.name.trim().length<2} onClick={()=>run(async()=>{await api.createCharacter(data.campaign.id,charForm);setCharForm({...charForm,name:'',player_name:''})})}><Plus/> Crear personatge</button></div>
        <div className="studio-card combat-link"><h3><Swords/> Connexió amb combat</h3>{activeCombat?<><p>Afegeix els membres actius a <strong>{activeCombat.name}</strong>. Els PG i les condicions quedaran sincronitzats.</p><button disabled={busy} onClick={()=>run(()=>api.addCharactersToCombat(activeCombat.id))}>Afegir grup al combat</button></>:<p>No hi ha cap combat actiu. Crea’l des de l’assistent de combat.</p>}</div></aside>
    </div>}

    {tab==='inventory'&&<div className="party-layout"><div>
      <details className="reward-inbox" open><summary>Botí pendent de guardar <b>{data.rewards.filter(x=>!x.claimed).length}</b></summary>{data.rewards.filter(x=>!x.claimed).map(reward=><article key={reward.id}><span><strong>{reward.title}</strong><small>{reward.items.map(x=>`${x.quantity??1}× ${x.name}`).join(' · ')}</small></span><button onClick={()=>run(()=>api.claimReward(reward.id))} disabled={busy}>✦ Guardar al grup</button></article>)}{!data.rewards.some(x=>!x.claimed)&&<p className="empty-state">No hi ha recompenses pendents.</p>}</details>
      <div className="inventory-list">{data.inventory.map(item=><article key={item.id}><span className="item-quantity">{item.quantity}×</span><div><strong>{item.name}</strong><small>{item.category} · {(item.weight*item.quantity).toFixed(1)} pes · {item.value} {item.currency_unit}</small>{item.description&&<p>{item.description}</p>}</div><select value={`${item.owner_type}:${item.owner_id??''}`} onChange={e=>transfer(item,e.target.value)}><option value="party:">Grup</option>{data.characters.map(c=><option key={c.id} value={`character:${c.id}`}>{c.name}</option>)}{data.locations.map(x=><option key={x.id} value={`location:${x.id}`}>📍 {x.name}</option>)}</select>{item.consumable&&<button onClick={()=>run(()=>api.consumeInventory(item.id,1))}>Consumir</button>}<button className="icon-button danger" onClick={()=>confirm(`Eliminar ${item.name}?`)&&run(()=>api.deleteInventory(item.id))}><Trash2/></button></article>)}</div>
    </div><aside className="party-side"><div className="studio-card"><h3><Plus/> Afegir objecte</h3><label>Nom<input value={itemForm.name} onChange={e=>setItemForm({...itemForm,name:e.target.value})}/></label><div className="two-columns"><label>Categoria<select value={itemForm.category} onChange={e=>setItemForm({...itemForm,category:e.target.value})}><option value="gear">Equip</option><option value="consumable">Consumible</option><option value="magic">Màgic</option><option value="supplies">Provisions</option><option value="quest">Missió</option></select></label><label>Propietari<select value={itemForm.owner_type} onChange={e=>setItemForm({...itemForm,owner_type:e.target.value,owner_id:''})}><option value="party">Grup</option><option value="character">Personatge</option><option value="location">Ubicació</option></select></label>{itemForm.owner_type!=='party'&&<label>Assignar a<select value={itemForm.owner_id} onChange={e=>setItemForm({...itemForm,owner_id:e.target.value})}><option value="">Tria...</option>{(itemForm.owner_type==='character'?data.characters:data.locations).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<label>Quantitat<input type="number" min="0.01" value={itemForm.quantity} onChange={e=>setItemForm({...itemForm,quantity:Number(e.target.value)})}/></label><label>Pes unitari<input type="number" min="0" step="0.1" value={itemForm.weight} onChange={e=>setItemForm({...itemForm,weight:Number(e.target.value)})}/></label><label>Valor (po)<input type="number" min="0" value={itemForm.value} onChange={e=>setItemForm({...itemForm,value:Number(e.target.value)})}/></label></div><label className="toggle-inline"><input type="checkbox" checked={itemForm.consumable} onChange={e=>setItemForm({...itemForm,consumable:e.target.checked})}/> Es pot consumir</label><button className="primary full" disabled={busy||itemForm.name.trim().length<2} onClick={()=>run(async()=>{await api.createInventory(data.campaign.id,{...itemForm,owner_id:itemForm.owner_type==='party'?null:itemForm.owner_id||null});setItemForm({...itemForm,name:'',quantity:1})})}><Plus/> Afegir a l’inventari</button></div></aside></div>}

    {tab==='treasury'&&<div className="treasury-layout"><div className="coin-grid">{currencies.map(unit=><article key={unit}><Coins/><span>{unit.toUpperCase()}</span><strong>{data.treasury[unit]}</strong></article>)}</div><div className="studio-card treasury-adjust"><h3>Moviment de tresoreria</h3><div className="three-columns"><label>Moneda<select value={currency} onChange={e=>setCurrency(e.target.value)}>{currencies.map(x=><option key={x}>{x}</option>)}</select></label><label>Quantitat<input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Motiu<input value={reason} onChange={e=>setReason(e.target.value)}/></label></div><p className="muted">Utilitza valors negatius per registrar compres o despeses. El saldo no pot quedar en negatiu.</p><button className="primary" disabled={busy||amount===0} onClick={()=>run(()=>api.adjustTreasury(data.campaign.id,currency,amount,reason))}>Registrar moviment</button></div></div>}
    {tab==='history'&&<div className="transaction-list">{data.inventory_transactions.map(tx=><article key={tx.id}><History/><span><strong>{tx.description}</strong><small>{new Date(tx.created_at).toLocaleString()} · {tx.kind}</small></span><b>{tx.currency_delta?`${tx.currency_delta>0?'+':''}${tx.currency_delta} ${tx.currency}`:tx.quantity_delta?`${tx.quantity_delta>0?'+':''}${tx.quantity_delta} u.`:'—'}</b></article>)}{!data.inventory_transactions.length&&<p className="empty-state">L’activitat d’inventari i tresoreria apareixerà aquí.</p>}</div>}
  </section>
}
